host:
    mysql: ${MYSQL_HOST:127.0.0.1}
    zoo1: ${ZOO1_HOST:127.0.0.1}
    zoo2: ${ZOO2_HOST:127.0.0.1}
    zoo3: ${ZOO3_HOST:127.0.0.1}

port:
    zoo1: ${ZOO1_PORT:2181}
    zoo2: ${ZOO2_PORT:2182}
    zoo3: ${ZOO3_PORT:2183}

spring:
    datasource:
        url: jdbc:mysql://${host.mysql}:3306/BILL?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: kevin
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            maximum-pool-size: 15
            initializationFailTimeout: 10000
    quartz:
        datasource:
            url: jdbc:mysql://${host.mysql}:3306/QRTZ_BILL?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
            username: root
            password: kevin
            driver-class-name: com.mysql.cj.jdbc.Driver
            hikari:
                maximum-pool-size: 15
                initializationFailTimeout: 10000
        properties:
            org:
                quartz:
                    scheduler:
                        instanceName: clusteredScheduler
                        instanceId: AUTO
                    jobStore:
                        class: org.quartz.impl.jdbcjobstore.JobStoreTX
                        driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
                        tablePrefix: QRTZ_
                        isClustered: true
                        clusterCheckinInterval: 10000
                        useProperties: false
                    threadPool:
                        class: org.quartz.simpl.SimpleThreadPool
                        threadCount: 10
                        threadPriority: 5
                        threadsInheritContextClassLoaderOfInitializingThread: true

dubbo:
    application:
        name: billDubboService
    protocol:
        name: dubbo
        port: 20889
        threadpool: cached
        serialization: kryo
    registry:
        protocol: zookeeper
        address: ${host.zoo1}:${port.zoo1},${host.zoo2}:${port.zoo2},${host.zoo3}:${port.zoo3}
    provider:
        version: 1.0.0
    consumer:
        version: 1.0.0

tcc:
    repository:
        domain: BILL
        tbSuffix: _BILL
    recover:
        maxRetryCount: 10
        recoverDuration: 30
        cronExpression: 0/15 * * * * ?
    datasource:
        url: jdbc:mysql://${host.mysql}:3306/BILL?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: kevin
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            maximum-pool-size: 15
            initializationFailTimeout: 10000
    isTested: true

logging:
    level:
        root: info
        org.jackson.puppy.demo.dubbo.bill.dao: debug
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss} %clr([%t]){cyan} %clr(%-5p) %clr(%C{3}){magenta} \(%F:%L\) - %m%n'
