CREATE DATABASE IF NOT EXISTS BILL DEFAULT CHARSET utf8 COLLATE utf8_general_ci;

USE BILL;

DROP TABLE IF EXISTS bill;
CREATE TABLE bill (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  order_number varchar(100) NOT NULL,
  agency_fee decimal(20,5) NOT NULL,
  status int(11) NOT NULL,
  created_date datetime(3) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY bill_order_number_idx (order_number) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS TCC_TRANSACTION_BILL;
CREATE TABLE TCC_TRANSACTION_BILL (
  TRANSACTION_ID int(11) NOT NULL AUTO_INCREMENT,
  DOMAIN varchar(100) DEFAULT NULL,
  GLOBAL_TX_ID varbinary(32) NOT NULL,
  BRANCH_QUALIFIER varbinary(32) NOT NULL,
  CONTENT varbinary(8000) DEFAULT NULL,
  STATUS int(11) DEFAULT NULL,
  TRANSACTION_TYPE int(11) DEFAULT NULL,
  RETRIED_COUNT int(11) DEFAULT NULL,
  CREATE_TIME datetime DEFAULT NULL,
  LAST_UPDATE_TIME datetime DEFAULT NULL,
  VERSION int(11) DEFAULT NULL,
  PRIMARY KEY (TRANSACTION_ID),
  UNIQUE KEY UX_TX_BQ (GLOBAL_TX_ID,BRANCH_QUALIFIER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
