host:
    mysql: ${MYSQL_HOST:127.0.0.1}
    rabbitmq: ${RABBITMQ_HOST:127.0.0.1}
    order: ${ORDER_HOST:127.0.0.1}

server:
    port: 9001

spring:
    datasource:
        url: jdbc:mysql://${host.mysql}:3306/CONFIRM?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: kevin
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            maximum-pool-size: 15
            initializationFailTimeout: 10000

    rabbitmq:
        username: kevin
        password: kevin
        host: ${host.rabbitmq}
        virtual-host: /
        port: 5672
        publisher-confirms: true
        publisher-returns: true
        listener:
            simple:
                acknowledge-mode: manual
    quartz:
        datasource:
            url: jdbc:mysql://${host.mysql}:3306/QRTZ_CONFIRM?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
            username: root
            password: kevin
            driver-class-name: com.mysql.cj.jdbc.Driver
            hikari:
                maximum-pool-size: 15
                initializationFailTimeout: 10000
        properties:
            org:
                quartz:
                    scheduler:
                        instanceName: clusteredScheduler
                        instanceId: AUTO
                    jobStore:
                        class: org.quartz.impl.jdbcjobstore.JobStoreTX
                        driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
                        tablePrefix: QRTZ_
                        isClustered: true
                        clusterCheckinInterval: 10000
                        useProperties: false
                    threadPool:
                        class: org.quartz.simpl.SimpleThreadPool
                        threadCount: 10
                        threadPriority: 5
                        threadsInheritContextClassLoaderOfInitializingThread: true

logging:
    level:
        root: info
        org.jackson.puppy.demo.dubbo.confirm.dao: info
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss} %clr([%t]){cyan} %clr(%-5p) %clr(%C{3}){magenta} \(%F:%L\) - %m%n'
